# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy the blog.html to the default Nginx web directory
COPY blog.html /usr/share/nginx/html/index.html

# Copy the image to the default Nginx web directory
COPY my-dog.jpg /usr/share/nginx/html/my-dog.jpg
